# generated by mBlock5 for CyberPi
# codes make you happy

import event, time, cyberpi, mbot2, mbuild

@event.start
def on_start():
    mbot2.EM_reset_angle("EM1")
    mbot2.EM_stop("ALL")
    mbuild.smart_camera.set_mode("color", 1)
    mbuild.smart_camera.open_light(1)
    mbot2.servo_set(90,"all")
    while True:
      cyberpi.console.println(mbot2.EM_get_angle("EM1"))
      if mbuild.smart_camera.detect_sign(1, 1):
        if mbuild.smart_camera.get_sign_x(1, 1) < 120:
          while not mbuild.smart_camera.is_lock_sign(1, 'x', 160, 1):
            mbot2.servo_add(3,"all")

        if mbuild.smart_camera.get_sign_x(1, 1) > 200:
          while not mbuild.smart_camera.is_lock_sign(1, 'x', 160, 1):
            mbot2.servo_add(-3,"all")

